# Setup
title: 'jnthnhrrr.github.io'
tagline: 'Thoughts on Computer Programming 🌻'
description:
url: 'https://jnthnhrrr.github.io'
paginate: 5
permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  typographic_symbols:
    ndash: –
    mdash: —

# About/contact
author:
  name: Jonathan Herrera
  url:
  email: jonathan.herrera@posteo.de

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Custom vars
version: 1.1.0
google_analytics_id: G-1HBN305G9K
repository_url: 'https://github.com/jnthnhrrr/jnthnhrrr.github.io/'

collections:
  series:
    output: true
    permalink: /:collection/:name


