# Setup
title:               'jonathan-scholbach.github.io'
tagline:             'Thoughts on Computer Programming 🌻'
description:
url:                 'https://jonathan-scholbach.github.io'
paginate:            5
permalink:           pretty
markdown:            kramdown
highlighter:         rouge
kramdown:
  input:             GFM
  hard_wrap: false
  syntax_highlighter: rouge

# About/contact
author:
  name:              Jonathan Scholbach
  url:
  email:             j.scholbach@posteo.de

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
version:             1.1.0
google_analytics_id: G-1HBN305G9K

collections:
  series:
    output: true
    permalink: /:collection/:name
